### ISSUE TITLE
API server configuration file is not a versioned format

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/cluster-capacity#27] opened 2017-02-10 02:43 UTC
The API server configuration file is not a versioned syntax.

see: https://github.com/kubernetes-incubator/cluster-capacity/blob/master/config/apiserver.yaml

If we are going to accept input files, we need to make them versioned.

**Comment by derekwaynecarr** [comment] 2017-02-10 02:54
I am a little apprehensive to invent a configuration file syntax since we lack a structured type yet for the apiserver itself.  Is it possible to reduce the set of options further?

**Comment by ingvagabund** [comment] 2017-02-10 09:21
All the options in the file are needed to create admissions controller. We can set some of the options to default without allowing any changes to them and remove them from the configuration file.

**Comment by aveshagarwal** [comment] 2017-02-10 14:17
I think having command flags and env vars both would be good with most of them set by default.

**Comment by aveshagarwal** [comment] 2017-03-02 20:36
I am closing this as apiserver config file option has been removed. Please reopen if you think the issue is not addressed

**Closed by aveshagarwal** 2017-03-02 20:36 UTC
Labels: priority-0
