### ISSUE TITLE
Need better build instructions

### ISSUE THREAD

**Issue by sferich888** [kubernetes-incubator/cluster-capacity#21] opened 2017-01-24 22:29 UTC
Not sure what I am doing, but `make build` does not provide enough instruction to build these components. 

```
go build -o hypercc github.com/ingvagabund/cluster-capacity/cmd/hypercc
../go/src/github.com/ingvagabund/cluster-capacity/vendor/github.com/ghodss/yaml/yaml.go:10:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/root/go/src/github.com/ingvagabund/cluster-capacity/vendor/gopkg.in/yaml.v2 (vendor tree)
	/usr/lib/golang/src/gopkg.in/yaml.v2 (from $GOROOT)
	/root/go/src/gopkg.in/yaml.v2 (from $GOPATH)
...
../go/src/github.com/ingvagabund/cluster-capacity/pkg/framework/strategy/strategy.go:9:2: cannot find package "k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache" in any of:
	/root/go/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache (vendor tree)
	/usr/lib/golang/src/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache (from $GOROOT)
	/root/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache (from $GOPATH)
make: *** [build] Error 1
```

**Comment by ingvagabund** [comment] 2017-01-25 12:20
What go version do you have? All the dependencies are under vendor. Looks like the directory is ignored.

**Comment by aveshagarwal** [comment] 2017-01-25 14:51
@sferich888 could you show what is the output of echo $GOPATH? I tried locally and it works fine.

**Comment by aveshagarwal** [comment] 2017-01-25 14:52
And yes what go version do you have? I tried it on fedora 25 without any issues.

**Comment by aveshagarwal** [comment] 2017-03-02 20:34
I am closing this as it seems to be working as expected. Please reopen if you think the issue is still not addressed.

**Closed by aveshagarwal** 2017-03-02 20:34 UTC
